name: ouw
version: '1.0-SNAPSHOT'
main: com.songro.ouw.Ouw
api-version: '1.21'
authors: [ notSongro_ ]
description:
  δύω (duo): greek word meaning duo

commands:
  setup:
    usage: /<command> <Player1Location_x> <Player1Location_y> <Player1Location_z> <Player2Location_x> <Player2Location_y> <Player2Location_z> <CopyGameRule?> <CopyDefaultSpawn?>
    description: Setup duel world